version: 0.1
phases: 
 install:
  commands:
   - npm run setup
   - npm start
   - npm run clean
   - aws cloudformation package --template-file Template.yaml 
                                --output-template-file NewSamTemplate.yaml
								--s3-bucket sample-ci-cd-pipeline

artifacts:
 type: zip
 files:
  - NewSamTemplate.yaml